#  IRIS Classification

## Classification of IRIS dataset using Neural Networks

In [2]:
#import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import linear_model, datasets,metrics
#draw plots in the browser
%matplotlib inline 

### IRIS data set
#### https://en.wikipedia.org/wiki/Iris_flower_data_set

In [3]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://upload.wikimedia.org/wikipedia/commons/4/41/Iris_versicolor_3.jpg", width=200, height=200)

In [4]:
# import Iris dataset from Scikit-Learn's datasets
iris = datasets.load_iris()

print ("Shape of the data ", iris.data.shape)
print ("Shape of the data ", iris.target_names)
print ("Attributes ", iris.feature_names)

#view first 5 rows
print (iris.data[range(5)])
print (iris.target[range(5)])

Shape of the data  (150, 4)
Shape of the data  ['setosa' 'versicolor' 'virginica']
Attributes  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [5]:
#show it as a table
df = pd.DataFrame(data=iris.data)
df.columns = [iris.feature_names]
df['Class'] = iris.target
df['Name'] = iris.target_names[iris.target]
df.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm) Class  \
0               5.1              3.5               1.4              0.2     0   
1               4.9              3.0               1.4              0.2     0   
2               4.7              3.2               1.3              0.2     0   
3               4.6              3.1               1.5              0.2     0   
4               5.0              3.6               1.4              0.2     0   

     Name  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [6]:
X = iris.data[:, :2]  # we only take the first two features.
Y = iris.target

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=0)
X_train.shape, y_train.shape
X_test.shape, y_test.shape

((45, 4), (45,))

### Neural Network using Keras + Tensorflow

In [9]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import to_categorical

Categorical data must be converted to a numerical form. 

In [10]:
def one_hot_encode_object_array(arr):
    '''One hot encode a numpy array of objects (e.g. strings)'''
    uniques, ids = np.unique(arr, return_inverse=True)
    return to_categorical(ids, len(uniques))

y_train_ohe = one_hot_encode_object_array(y_train)
y_test_ohe= one_hot_encode_object_array(y_test)

### <span style="color:cornflowerblue">Exercise:</span> 
#### Define and Train a Neural Network that can classify IRIS flowers

In [63]:
y_train

array([1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1,
       2, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0,
       2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1,
       1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [135]:
from keras.layers import Dense
import numpy as np
def create_iris_neural_network():
    model = Sequential()
    model.add(Dense(16, input_shape=(4,), activation='sigmoid'))
    model.add(Activation('sigmoid'))
    model.add(Dense(3, activation='sigmoid'))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

model = create_iris_neural_network()
model.fit(X_train, y_train_ohe, epochs=100)

print((np.argmax(y_test_ohe, axis=1) == np.argmax(model.predict(X_test), axis=1)).mean())
np.argmax(model.predict(X_test), axis=1)

Epoch 1/100
4/4 [==============================] - 1s 2ms/step - loss: 1.1032 - accuracy: 0.3238
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 1.1023 - accuracy: 0.3238
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 1.1013 - accuracy: 0.3238
Epoch 4/100
4/4 [==============================] - 0s 9ms/step - loss: 1.1006 - accuracy: 0.3238
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1002 - accuracy: 0.3238
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0997 - accuracy: 0.3238
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0991 - accuracy: 0.3238
Epoch 8/100
4/4 [==============================] - 0s 2ms/step - loss: 1.0985 - accuracy: 0.3238
Epoch 9/100
4/4 [==============================] - 0s 2ms/step - loss: 1.0980 - accuracy: 0.2571
Epoch 10/100
4/4 [==============================] - 0s 2ms/step - loss: 1.0976 - accuracy: 0.2381
Epoch 11/100
4/4 [===========

array([2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2], dtype=int64)